### Test adding an entry to a patient
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{  "date": "2015-01-02",
        "type": "Hospital",
        "specialist": "TESTY MCTESTFACE",
        "diagnosisCodes": ["S62.5"],
        "description":"TEST TEST TEST TEST",
        "discharge": {
          "date": "2077-01-16",
          "criteria": "TEST"
        }
        }